dv_tutorial:
  outputs:
    dev:
      type: fal
      db_profile: dev_postgres
    dev_postgres:
      type: postgres
      user: dev
      pass: abcd
      port: 5432
      schema: dbo
      threads: 1
      host: sqlNode1
      dbname: dv_test
  target: dev
